In [354]:
np.__version__

'1.26.4'

# Create a List

In [355]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [356]:
type(my_list)

list

# Convert list to array 

In [357]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [358]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


# Arange function

In [359]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [360]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [361]:
np.arange(8, 20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [362]:
np.arange(20, 8)

array([], dtype=int64)

In [363]:
np.arange(-20, 8) # 1st arg < 2nd org

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [364]:
n = np.arange(-20, 8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

# zeros() function

In [365]:
np.zeros(3) # 1d array

array([0., 0., 0.])

In [366]:
np.zeros(3, dtype=int) # 1d array

array([0, 0, 0])

In [367]:
z = np.zeros(5)
z # 1d array

array([0., 0., 0., 0., 0.])

In [368]:
np.zeros((2, 2)) # 2d array

array([[0., 0.],
       [0., 0.]])

In [369]:
np.zeros((3,3), dtype=int) # 2d array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [370]:
np.zeros((5,9), dtype=int) # 5 * 9 d array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [371]:
np.ones(3)

array([1., 1., 1.])

# ones() function

In [372]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [373]:
np.ones((10,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# rand() function

In [374]:
random.rand(3,2)

NameError: name 'random' is not defined

In [375]:
np.random.rand(2)

array([0.52200603, 0.65936549])

In [376]:
np.random.rand(2)

array([0.72789055, 0.19740996])

In [377]:
np.random.rand(3)

array([0.53154195, 0.74776472, 0.01102435])

In [378]:
np.random.rand(2,3)

array([[0.74838437, 0.56638218, 0.55052066],
       [0.39316419, 0.63018184, 0.57494479]])

# randint() function

In [379]:
np.random.randint(3)

2

In [380]:
np.random.randint(2, 10) # here 2 is inclusive and 10 exlusive

6

In [381]:
np.random.randint(2, 10, 4) # It generates 4 random numbers b/w 2 and 10. here 2 is inclusive and 10 exlusive

array([6, 6, 2, 3])

In [382]:
np.random.randint(-30, 20, 10)

array([ -9,   6, -16,  -4,   4,   9,  -4,  16, -17,  19])

In [383]:
np.random.randint(10, 40,(10, 10))

array([[27, 38, 13, 29, 22, 35, 26, 23, 32, 34],
       [31, 14, 38, 16, 10, 17, 26, 22, 23, 34],
       [39, 31, 39, 11, 25, 12, 31, 30, 21, 20],
       [18, 32, 26, 32, 36, 23, 24, 19, 33, 18],
       [32, 18, 25, 19, 16, 19, 27, 17, 29, 32],
       [11, 21, 32, 28, 11, 18, 16, 27, 38, 13],
       [30, 16, 19, 28, 31, 32, 24, 34, 10, 17],
       [30, 34, 21, 26, 11, 21, 37, 10, 24, 30],
       [27, 21, 20, 18, 11, 19, 22, 36, 37, 18],
       [14, 26, 13, 17, 18, 34, 12, 33, 13, 31]])

In [384]:
m = np.random.randint(10, 40, (10, 10))
m

array([[34, 12, 18, 20, 21, 33, 19, 39, 11, 19],
       [16, 35, 28, 20, 27, 20, 12, 35, 20, 30],
       [27, 23, 26, 39, 13, 17, 32, 18, 17, 34],
       [24, 16, 30, 26, 17, 31, 27, 32, 34, 19],
       [32, 13, 16, 10, 15, 32, 31, 39, 39, 28],
       [22, 24, 21, 15, 31, 13, 35, 14, 20, 31],
       [20, 30, 28, 28, 23, 10, 15, 35, 30, 16],
       [15, 14, 31, 25, 34, 18, 38, 18, 35, 12],
       [12, 31, 15, 21, 38, 37, 34, 25, 15, 10],
       [25, 31, 17, 31, 13, 39, 34, 29, 23, 37]])

# Slicing 

In [385]:
arr 

array([0, 1, 2, 3, 4, 5])

In [386]:
arr.reshape(2,3) 

array([[0, 1, 2],
       [3, 4, 5]])

In [387]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [388]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [389]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

# Slicing in metrix

In [390]:
m

array([[34, 12, 18, 20, 21, 33, 19, 39, 11, 19],
       [16, 35, 28, 20, 27, 20, 12, 35, 20, 30],
       [27, 23, 26, 39, 13, 17, 32, 18, 17, 34],
       [24, 16, 30, 26, 17, 31, 27, 32, 34, 19],
       [32, 13, 16, 10, 15, 32, 31, 39, 39, 28],
       [22, 24, 21, 15, 31, 13, 35, 14, 20, 31],
       [20, 30, 28, 28, 23, 10, 15, 35, 30, 16],
       [15, 14, 31, 25, 34, 18, 38, 18, 35, 12],
       [12, 31, 15, 21, 38, 37, 34, 25, 15, 10],
       [25, 31, 17, 31, 13, 39, 34, 29, 23, 37]])

In [391]:
b = np.random.randint(10,20,(5,4))
b

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

In [392]:
b[:]

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

In [393]:
b[1:4]

array([[14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10]])

In [394]:
type(b)

numpy.ndarray

In [395]:
b.ndim

2

In [396]:
b[-5:-1]

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10]])

In [397]:
b[-1:]

array([[16, 13, 17, 17]])

In [398]:
b

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

In [399]:
b[-1:]

array([[16, 13, 17, 17]])

In [400]:
b[:-1]

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10]])

In [401]:
b

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

In [402]:
b[1,-1]

15

In [403]:
b

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

In [411]:
b[-4,-2]

14

In [412]:
b


array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

In [413]:
b[-4:2]

array([[14, 18, 14, 15]])

In [414]:
b[:]

array([[14, 12, 17, 13],
       [14, 18, 14, 15],
       [19, 19, 12, 19],
       [19, 10, 15, 10],
       [16, 13, 17, 17]])

# Numpy operations

In [418]:
a = np.random.randint(10, 20, 10)
a

array([12, 13, 11, 10, 14, 14, 17, 15, 10, 17])

In [419]:
id(a)

5076051472

In [420]:
arr

array([0, 1, 2, 3, 4, 5])

In [422]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [423]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [424]:
arr[:4]

array([0, 1, 2, 3])

In [425]:
arr2[:]

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [427]:
arr2[0:5]

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28]])

In [428]:
arr2

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [430]:
arr2[1,4]

78

In [431]:
arr2

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [433]:
arr2[-5,5]

60

In [434]:
arr2

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [405]:
arr.min()

0

In [406]:
arr.mean()

2.5

In [407]:
arr.max()

5

In [408]:
arr

array([0, 1, 2, 3, 4, 5])

In [409]:
m

array([[34, 12, 18, 20, 21, 33, 19, 39, 11, 19],
       [16, 35, 28, 20, 27, 20, 12, 35, 20, 30],
       [27, 23, 26, 39, 13, 17, 32, 18, 17, 34],
       [24, 16, 30, 26, 17, 31, 27, 32, 34, 19],
       [32, 13, 16, 10, 15, 32, 31, 39, 39, 28],
       [22, 24, 21, 15, 31, 13, 35, 14, 20, 31],
       [20, 30, 28, 28, 23, 10, 15, 35, 30, 16],
       [15, 14, 31, 25, 34, 18, 38, 18, 35, 12],
       [12, 31, 15, 21, 38, 37, 34, 25, 15, 10],
       [25, 31, 17, 31, 13, 39, 34, 29, 23, 37]])

In [ ]:
mat = np.arange(0,100).reshape(10,10)
mat


In [436]:
arr2

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [437]:
arr2[::-2]

array([[72,  8,  2, 32, 40,  8, 56, 55, 19, 71],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37]])

In [438]:
arr2[::-3]

array([[72,  8,  2, 32, 40,  8, 56, 55, 19, 71],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [84, 42,  7, 99, 63, 33, 52, 41, 70, 86]])

In [440]:
arr2

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17],
       [30, 81, 44, 35,  4, 26, 86, 26, 82, 82],
       [42, 63, 49, 58, 67, 44, 45,  3, 72, 42],
       [72,  8,  2, 32, 40,  8, 56, 55, 19, 71]])

In [441]:
arr2[:-3]

array([[84, 42,  7, 99, 63, 33, 52, 41, 70, 86],
       [98, 14, 90, 58, 78,  2, 12, 26,  2, 37],
       [77, 76, 34,  4, 71, 76, 54, 32,  7, 99],
       [65, 54, 22, 77, 39, 27, 12, 60, 41, 38],
       [28, 44, 78, 38,  6, 33, 57, 92, 43, 28],
       [94, 18, 97, 27, 35, 60, 10, 38, 80, 85],
       [48, 24, 26,  9, 40, 99, 33,  7, 80, 17]])

In [442]:
arr

array([0, 1, 2, 3, 4, 5])

In [443]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [444]:
arr.reshape(2,3, order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [445]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [446]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [447]:
arr

array([0, 1, 2, 3, 4, 5])

# Slicing & Indexing

In [448]:
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [449]:
row = 4
col = 5

In [450]:
mat[row, col]

45

In [451]:
mat[4,5]

45

In [452]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [453]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [454]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [456]:
col = 6
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [457]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [458]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [459]:
mat[:, 8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [460]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [461]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [462]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [463]:
row

4

In [464]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [465]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [466]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [467]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [468]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [469]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [470]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [471]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [472]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [473]:
row

4

In [474]:
col

6

In [475]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

mat

In [477]:
mat[1,4]

14

In [478]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [479]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [480]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [481]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [482]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [483]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [484]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [485]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [486]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [487]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [490]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [491]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [492]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [493]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [494]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [495]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [496]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [497]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [498]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [499]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [500]:
mat[1:2,2:4] 

array([[12, 13]])

In [501]:
mat[2:3,2:3] 

array([[22]])

In [502]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [503]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [504]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [505]:
mat[2:3,4:5]

array([[24]])

# Masking

In [506]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [507]:
id(mat)

5076057424

In [508]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [509]:
type(mat[mat<50])mat[mat<=50]

numpy.ndarray

In [510]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [511]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [512]:
mat[mat==50] 

array([50])

In [513]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [515]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [516]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [517]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [518]:
a4 = mat[mat==50]
a4

array([50])