# Numpy Crash Course

In [2]:
import numpy as np
np.__version__

'1.26.4'

# Creating Arrays 

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

# array() function

In [5]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(3.0)

array([0., 1., 2.])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20, 10)

array([], dtype=int64)

In [14]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(30, 20)

array([], dtype=int64)

In [17]:
ar = np.arange(-30, 20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange(10, 10)

array([], dtype=int64)

In [20]:
# np.arange() -> empty function throws error. TypeError: arange() requires stop to be specified.

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
# np.arange(10,30,5,8) -> arange function supports only 3 params. start, end, step.

# zeros() function

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [26]:
zeros = np.zeros([2,2])
zeros

array([[0., 0.],
       [0., 0.]])

In [28]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros((10, 30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [31]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
n = (6,7)
n1 = (6,8)
np.zeros(n1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros(n, dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
n

(6, 7)

In [37]:
n1

(6, 8)

In [38]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#  ones() function

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [41]:
n


(6, 7)

In [42]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [44]:
np.ones(n, dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

# range() function

# range() function

In [45]:
range(5)

range(0, 5)

In [47]:
r = range(5)
r

range(0, 5)

In [48]:
for i in range(5):
    print(i)

0
1
2
3
4


In [49]:
list(range(5))

[0, 1, 2, 3, 4]

In [50]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
list(range(1,10, 3))

[1, 4, 7]

In [52]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# rand() function

In [53]:
np.random.rand(10)

array([0.71167174, 0.66149613, 0.48762718, 0.93519166, 0.67506605,
       0.53405128, 0.75155129, 0.0405138 , 0.11275753, 0.88839118])

In [55]:
np.random.rand(1,10)

array([[0.07243722, 0.94281134, 0.25576275, 0.03645723, 0.49917744,
        0.68422723, 0.52624717, 0.39543976, 0.46464868, 0.93754401]])

In [60]:
np.random.rand(2, 10)

array([[0.93161328, 0.70632836, 0.60071661, 0.23101107, 0.87660604,
        0.03581537, 0.3427346 , 0.22815468, 0.56880149, 0.52952887],
       [0.50819492, 0.16527843, 0.46179968, 0.1377851 , 0.15912722,
        0.79436162, 0.19322665, 0.41792259, 0.08350661, 0.06563348]])

# randint() function

In [62]:
np.random.randint(10)

6

In [63]:
np.random.randint(2,20)

15

In [65]:
np.random.randint(10,20,5)

array([15, 17, 10, 18, 14])

In [67]:
np.random.randint(1,6,6)

array([3, 1, 2, 3, 3, 2])

In [68]:
np.random.randint(30,20,10)

ValueError: low >= high

In [69]:
np.random.randint(-30,20,10)

array([-23,  11,   4,  -7, -13, -24, -18, -18,   6, -15])

In [70]:
np.random.randint(10,40)

17

In [72]:
np.random.randint(10,40,(2,2))

array([[25, 18],
       [27, 13]])

In [73]:
np.random.randint(10,40,(3,3))

array([[32, 25, 23],
       [20, 18, 27],
       [24, 32, 22]])

In [74]:
np.random.randint(10,40,(5,5))

array([[21, 39, 25, 14, 37],
       [38, 26, 34, 17, 13],
       [16, 36, 18, 14, 15],
       [31, 27, 13, 23, 29],
       [34, 27, 37, 13, 37]])

In [75]:
np.random.randint(10,40,(10,10))

array([[25, 28, 35, 36, 21, 13, 30, 36, 32, 13],
       [27, 38, 18, 24, 12, 26, 10, 31, 25, 19],
       [16, 28, 19, 35, 14, 16, 13, 12, 13, 22],
       [19, 39, 35, 13, 27, 39, 29, 23, 24, 30],
       [20, 18, 14, 10, 32, 28, 16, 37, 22, 30],
       [28, 26, 37, 16, 23, 35, 12, 13, 19, 36],
       [39, 37, 21, 18, 16, 21, 13, 33, 39, 21],
       [14, 27, 10, 33, 35, 19, 37, 19, 18, 21],
       [19, 24, 25, 22, 33, 10, 29, 32, 10, 27],
       [38, 31, 27, 21, 18, 29, 38, 11, 29, 17]])

In [76]:
np.random.randint(1,100,(12,12))

array([[37, 45, 24, 85, 12, 83, 36, 92, 14, 65, 55,  1],
       [92, 84, 23, 50, 85, 61, 23,  1, 52, 70, 27, 14],
       [62, 93,  5, 84, 29, 74,  6, 55, 70, 63, 20, 22],
       [ 4, 35, 13, 41, 34, 85, 50, 79, 64, 76, 72, 37],
       [78, 33,  5, 11, 34, 68, 29, 24,  8, 67,  8, 23],
       [ 7, 73, 27, 78, 89, 62, 84, 11,  1, 63, 27, 11],
       [16, 81, 81, 28, 75, 31, 28, 72, 91,  8,  3, 26],
       [47, 18, 59, 63, 69, 30,  7, 51, 97, 39, 49,  5],
       [39, 39, 10, 79, 76, 91, 11, 47, 51, 87, 71, 87],
       [97, 67, 21, 61, 48, 14, 53, 27, 38, 84, 30, 30],
       [58, 88, 34, 47, 77, 58, 54, 92,  6, 26, 93, 17],
       [70, 43, 51, 84, 92, 96, 84, 53, 98, 20, 76,  2]])

# reshape() function 

In [77]:
np.arange(1, 13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [81]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])

In [82]:
type(b)

numpy.ndarray

In [83]:
b

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])

# slicing & indexing

In [84]:
b[:]

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])

In [85]:
b[1:3]

array([[16, 10, 17, 10],
       [14, 13, 11, 14]])

In [86]:
b

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])

In [87]:
b[1,2]

17

In [88]:
b

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])

In [89]:
b[1,3]

10

In [90]:
b[1, -1]

10

In [91]:
b

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])

In [92]:
b[2:3]

array([[14, 13, 11, 14]])

In [93]:
b

array([[17, 10, 14, 14],
       [16, 10, 17, 10],
       [14, 13, 11, 14],
       [15, 16, 16, 19],
       [16, 12, 19, 14]])