In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [4]:
print(arr[0] + arr[1])

3


In [5]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
arr_2d[1,4]

10

In [8]:
arr_2d[0,0]

1

In [12]:
arr_3d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr_3d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [13]:
arr_3d.ndim

3

In [14]:
arr_5d = np.array([1,2,3,4,5], ndmin=5)
print(arr_5d)

[[[[[1 2 3 4 5]]]]]


In [15]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
arr_2d[0,4]

5

In [21]:
arr_2d[1,2]

8

In [22]:
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [23]:
arr_3d[0,1,2]

8

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
arr[1:1]

array([], dtype=int64)

In [28]:
arr[1:10]

array([2, 3, 4, 5])